name: Master Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Set the release version'
        required: true
        default: '1.0.0'

jobs:
  bump-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml build twine

      - name: Update version
        run: |
          python update_version.py ${{ inputs.version }}

      - name: Build and publish to PyPI
        run: |
          python -m build
          python -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Confirm version update
        run: |
          echo "Release version set to ${{ inputs.version }}."
