name: Release Workflow

on:
  push:
    branches:
      - master

jobs:
  bump-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install bump-my-version build twine

      - name: Show pyproject.toml before version bump
        run: cat pyproject.toml

      - name: Bump stable release version
        run: bump-my-version patch

      - name: Show pyproject.toml after version bump
        run: cat pyproject.toml

      - name: Build the package
        run: python -m build

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*
