name: Publish Pre-Release to PyPI

on:
  push:
    branches:
      - dev

jobs:
  publish:
    name: Publish Pre-Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # or '3.10'

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump2version build twine

      - name: Bump pre-release version
        run: bump2version --no-tag pre-release  # Automatically increments alpha pre-release

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*

      - name: Create GitHub Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump_version.outputs.new_version }}
          name: "Pre-Release ${{ steps.bump_version.outputs.new_version }}"
          body: "Automated pre-release"
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
