name: Master Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Set the release version'
        required: true
        default: '1.0.0'

jobs:
  bump-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Bump version
        id: bump
        uses: callowayproject/bump-my-version@master
        env:
          BUMPVERSION_TAG: "true"
        with:
          args: ${{ inputs.version }}
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Build and publish to PyPI
        run: |
          python -m build
          python -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Confirm bump
        run: |
          echo "Release version set to ${{ inputs.version }}."
