name: Dev Pre-Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Set the pre-release version for dev'
        required: true
        default: '1.0.0-alpha'

jobs:
  bump-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: dev  # Ensure it checks out the dev branch

      - name: Update version in version_dev.json
        run: |
          echo "Updating dev version to ${{ inputs.version }}"
          jq ".version = \"${{ inputs.version }}\"" src/batFramework/version_dev.json > src/batFramework/version_dev.json.tmp
          mv src/batFramework/version_dev.json.tmp src/batFramework/version_dev.json

      - name: Commit version update
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add src/batFramework/version_dev.json
          git commit -m "Update dev version to ${{ inputs.version }}"
          git push origin dev

      - name: Build and publish to Test PyPI
        run: |
          python -m build
          python -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

      - name: Confirm version update
        run: |
          echo "Dev pre-release version set to ${{ inputs.version }}."
