name: Master Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Set the release version for master'
        required: true
        default: '1.0.0'

jobs:
  bump-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: master  # Ensure it checks out the master branch

      - name: Update version in version_master.json
        run: |
          echo "Updating master version to ${{ inputs.version }}"
          jq ".version = \"${{ inputs.version }}\"" src/batFramework/version_master.json > src/batFramework/version_master.json.tmp
          mv src/batFramework/version_master.json.tmp src/batFramework/version_master.json

      - name: Update version in pyproject.toml
        run: |
          echo "Updating pyproject.toml version to ${{ inputs.version }}"
          sed -i "s/^version = .*/version = \"${{ inputs.version }}\"/" pyproject.toml

      - name: Commit version updates
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add src/batFramework/version_master.json pyproject.toml
          git commit -m "Update master version to ${{ inputs.version }}"
          git push origin master

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build and publish to PyPI
        run: |
          python -m build
          python -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

      - name: Confirm version update
        run: |
          echo "Master release version set to ${{ inputs.version }}."
